git:
  depth: 1
  quiet: true

os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - llvm
      - cmake
    update: true

env:
  - PATH="/usr/local/opt/llvm/bin:${PATH}"

matrix:
  include:
    - language: c++
      script:
        - mkdir -p build && cd build
        - cmake .. -DBUILD_INTEGRATION_TESTS=OFF -DBUILD_EXAMPLES=OFF
        - make check
        - cmake .. -DBUILD_INTEGRATION_TESTS=ON -DBUILD_EXAMPLES=ON
        - pushd ../test && install/bin/tyr path.tyr -bind-lang=c -emit-llvm -out-dir=./c -file-utils -base64 && popd
        - make c_test && ./test/c_test
        - make graph_example && ./example/graph/graph_example
    - language: rust
      script:
        - mkdir -p build && cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=../test/install -DBUILD_INTEGRATION_TESTS=OFF
        - make check install
        - pushd ../test && install/bin/tyr path.tyr -bind-lang=rust -emit-llvm -out-dir=./rust -file-utils -base64 && popd
        - pushd ../test/rust && cargo test

