git:
  depth: 1
  quiet: true

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode10.1

jobs:
  include:
    - stage: build
      script: mkdir -p build && cd build && cmake .. && make check install
    - stage: test
      script: cd test && make test_c && make_test_python && make_x_lang

