git:
  depth: 1
  quiet: true

language: c++

os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - llvm
      - cmake
    update: true

env:
  - PATH="/usr/local/opt/llvm/bin:${PATH}"

jobs:
  include:
    - stage: build
      script: mkdir -p build && cd build && cmake .. && make check install && cd test && make test_c && make_test_python && make_x_lang

