git:
  depth: 1
  quiet: true

language: c++

os: osx
osx_image: xcode10.1
addons:
  homebrew:
    packages:
      - llvm
      - cmake
      - python
    update: true

env:
  - PATH="/usr/local/opt/llvm/bin:${PATH}"

jobs:
  include:
    - stage: build
      script: mkdir -p build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=../test -DBUILD_INTEGRATION_TESTS=OFF && make check install

